resolver: lts-7.14
compiler: ghc-8.0.2

packages:
- .
- apps/hello
- apps/lda
- apps/rdd-ops
- apps/argv
- apps/dataframe

extra-deps:
 - choice-0.2.0
 - inline-c-0.5.6.1
 - inline-java-0.6.2
 - jni-0.3.0
 - jvm-0.2.0
 - jvm-streaming-0.2
 - thread-local-storage-0.1.1

explicit-setup-deps:
  bench: true

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/sparkle
  run-args: ["--net=bridge"]
  stack-exe: image
