require-stack-version: ">= 1.4"

resolver: nightly-2017-12-01

packages:
- .
- apps/argv
- apps/bench
- apps/dataframe
- apps/hello
- apps/lda
- apps/rdd-ops

extra-deps:
- mmorph-1.0.9
- streaming-0.1.4.5

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]

docker:
  enable: false
  image: tweag/sparkle
  run-args: ["--net=bridge"]
  stack-exe: image
