resolver: lts-6.21

packages:
- .
- apps/hello
- apps/lda
- apps/rdd-ops
- apps/argv
extra-deps:
- thread-local-storage-0.1.0.3
- jni-0.2.2
- jvm-0.1.2

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/sparkle
  run-args: ["--net=bridge"]
  stack-exe: image
