resolver: lts-8.8

packages:
- .
- apps/argv
- apps/bench
- apps/dataframe
- apps/hello
- apps/lda
- apps/rdd-ops

extra-deps:
 - jni-0.3.0
 - jvm-0.2.0
 - inline-java-0.6.3

explicit-setup-deps:
  bench: true

nix:
  # Requires Stack >= 1.2.
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/sparkle
  run-args: ["--net=bridge"]
  stack-exe: image
