version: 2

jobs:
  build:
    docker:
      - image: nixos/nix
    working_directory: ~/sparkle
    steps:
      - checkout
      - run:
          name: Install Stack
          command: |
            apk update --no-progress && apk --no-progress add ca-certificates bash
            nix-env -f nixpkgs.nix -iA stack
            mkdir -p ~/.stack
            echo "nix: {enable: true}" > ~/.stack/config.yaml
      - restore_cache:
          key: sparkle-stack-dependencies-{{ arch }}-
      - run:
          name: Build dependencies
          command: |
            stack --no-terminal build --only-snapshot --prefetch --no-haddock --test --bench
            find . -name "*.cabal" -o -name "stack.yaml" -type f | sort | xargs cat > /tmp/stack-deps
      - save_cache:
          key: sparkle-stack-dependencies-{{ arch }}-{{ checksum "/tmp/stack-deps" }}
          paths:
            - ~/.stack
      - run:
          name: Build project
          command: stack --no-terminal build --pedantic
      - run:
          name: Smoke test using sparkle-example-hello
          command: |
            stack --no-terminal exec -- sparkle package sparkle-example-hello
            stack --no-terminal exec -- spark-submit --master 'local[1]' sparkle-example-hello.jar
